version: "3.9"

services:
  reverse_proxy:
    build: ./reverse_proxy
    container_name: reverse_proxy
    ports:
      - 9090:80

  server_main: 
    build: ./server_main
    container_name: server_main
    ports:
      - 8081:80

  server_app: 
    build: ./server_app
    container_name: server_app
    ports:
      - 8082:80
