FROM httpd:2.4
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./proxy-html.conf /usr/local/apache2/conf/extra/proxy-html.conf
COPY ./reverse-proxy-httpd.conf /usr/local/apache2/conf/extra/reverse-proxy-httpd.conf
